# Generated by Django 5.1.4 on 2025-08-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_event_services_eventservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='services',
            field=models.ManyToManyField(related_name='events', through='core.EventService', to='core.service'),
        ),
    ]
